services:
  app:
    build: .
    container_name: secretario_virtual_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - session_data:/usr/src/app/session_data
      - user_data:/usr/src/app/data
    ports:
      - "3000:3000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  session_data:
  user_data:
