name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        env:
          OPENAI_API_KEY: dummy
          SKIP_OPENAI_CALLS: 'true'
        run: |
          node scripts/test-setup.js
          node scripts/test-security.js
          node scripts/test-audio.js
          node scripts/test-image.js
      - name: Test endpoints (smoke)
        env:
          DISABLE_WHATSAPP: 'true'
          OPENAI_API_KEY: dummy
          SKIP_OPENAI_CALLS: 'true'
        run: |
          node index.js &
          APP_PID=$!
          sleep 2
          node scripts/test-endpoints.js || (kill $APP_PID; exit 1)
          kill $APP_PID
      - name: OpenAI connectivity (optional)
        if: ${{ secrets.OPENAI_API_KEY != '' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_TEST_MODEL: gpt-4o-mini
        run: npm run test-openai

      - name: Audit (prod severity high)
        run: npm audit --omit=dev --audit-level=high || true

